name: CI - Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Permission gradlew
        run: chmod +x gradlew

      - name: Run lint
        run: ./gradlew lint

      - name: Upload lint report
        uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results-debug.html

      - name: Build and test Android app
        run: ./gradlew clean build test