name: CI - Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Permission gradlew
        run: chmod +x gradlew

      - name: Run tests and static analysis
        run: ./gradlew ktlintCheck detekt

      - name: Build and test Android app
        run: ./gradlew clean build test