name: CI - Pull Request

on:
  pull_request:
    branches:
      branches: [ "main","develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests and static analysis
        run: ./gradlew ktlintCheck detekt